
import React, { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ShieldCheck, Bot, FileText, RefreshCw } from 'lucide-react';

const FeatureShowcase = () => {
  const [activeTab, setActiveTab] = useState("plagiarism");

  return (
    <div className="w-full max-w-6xl mx-auto px-6 lg:px-8 py-12">
      <Tabs defaultValue="plagiarism" className="w-full" onValueChange={setActiveTab}>
        <TabsList className="grid grid-cols-3 w-full max-w-lg mx-auto mb-10">
          <TabsTrigger value="plagiarism">Plagiarism Check</TabsTrigger>
          <TabsTrigger value="detection">AI Detection</TabsTrigger>
          <TabsTrigger value="humanize">AI Humanizer</TabsTrigger>
        </TabsList>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <TabsContent value="plagiarism" className="mt-0 order-2 lg:order-1">
            <div className="space-y-6 animate-fade-in">
              <div className="inline-flex items-center space-x-2 bg-primary/10 text-primary px-3 py-1 rounded-full text-sm">
                <ShieldCheck size={16} />
                <span>Plagiarism Checker</span>
              </div>
              <h3 className="text-3xl font-bold tracking-tighter">Ensure Complete Originality</h3>
              <p className="text-muted-foreground text-lg">
                Our advanced plagiarism detection system scans your text against billions of sources, 
                highlighting any duplicate content and providing exact source links.
              </p>
              <ul className="space-y-3">
                <FeaturePoint>Real-time scanning against vast databases</FeaturePoint>
                <FeaturePoint>Highlights matching text with exact percentages</FeaturePoint>
                <FeaturePoint>Direct links to original sources</FeaturePoint>
                <FeaturePoint>Downloadable detailed reports</FeaturePoint>
              </ul>
            </div>
          </TabsContent>

          <TabsContent value="detection" className="mt-0 order-2 lg:order-1">
            <div className="space-y-6 animate-fade-in">
              <div className="inline-flex items-center space-x-2 bg-primary/10 text-primary px-3 py-1 rounded-full text-sm">
                <Bot size={16} />
                <span>AI Content Detection</span>
              </div>
              <h3 className="text-3xl font-bold tracking-tighter">Identify AI-Generated Content</h3>
              <p className="text-muted-foreground text-lg">
                Our AI detection tool analyzes text patterns to determine whether content 
                was written by a human or generated by AI tools like ChatGPT or GPT-4.
              </p>
              <ul className="space-y-3">
                <FeaturePoint>High accuracy detection algorithm</FeaturePoint>
                <FeaturePoint>Confidence scores with detailed breakdown</FeaturePoint>
                <FeaturePoint>Identifies specific AI patterns</FeaturePoint>
                <FeaturePoint>Works with all major AI writing tools</FeaturePoint>
              </ul>
            </div>
          </TabsContent>

          <TabsContent value="humanize" className="mt-0 order-2 lg:order-1">
            <div className="space-y-6 animate-fade-in">
              <div className="inline-flex items-center space-x-2 bg-primary/10 text-primary px-3 py-1 rounded-full text-sm">
                <RefreshCw size={16} />
                <span>AI Humanizer</span>
              </div>
              <h3 className="text-3xl font-bold tracking-tighter">Transform AI Text to Human Writing</h3>
              <p className="text-muted-foreground text-lg">
                Our humanizer tool transforms AI-generated content into natural, human-like writing 
                that bypasses detection while maintaining clarity and intent.
              </p>
              <ul className="space-y-3">
                <FeaturePoint>Preserves original meaning while rewriting</FeaturePoint>
                <FeaturePoint>Adds natural human writing patterns</FeaturePoint>
                <FeaturePoint>Maintains readability and coherence</FeaturePoint>
                <FeaturePoint>Multiple style options for various contexts</FeaturePoint>
              </ul>
            </div>
          </TabsContent>

          <div className="order-1 lg:order-2">
            <div className="relative bg-gradient-to-br from-muted/50 via-muted to-muted/50 rounded-2xl p-6 h-[400px] overflow-hidden flex items-center justify-center">
              {activeTab === "plagiarism" && (
                <div className="animate-fade-in w-full max-w-md">
                  <FeaturePreviewPlagiarism />
                </div>
              )}
              
              {activeTab === "detection" && (
                <div className="animate-fade-in w-full max-w-md">
                  <FeaturePreviewDetection />
                </div>
              )}
              
              {activeTab === "humanize" && (
                <div className="animate-fade-in w-full max-w-md">
                  <FeaturePreviewHumanize />
                </div>
              )}
            </div>
          </div>
        </div>
      </Tabs>
    </div>
  );
};

const FeaturePoint = ({ children }: { children: React.ReactNode }) => (
  <li className="flex items-center gap-2">
    <div className="w-5 h-5 rounded-full bg-primary/20 flex items-center justify-center">
      <div className="w-2 h-2 rounded-full bg-primary"></div>
    </div>
    <span>{children}</span>
  </li>
);

const FeaturePreviewPlagiarism = () => (
  <div className="bg-white shadow-lg rounded-xl p-6 w-full">
    <div className="space-y-4">
      <div className="h-6 w-3/4 bg-muted rounded-md animate-pulse"></div>
      <div className="space-y-2">
        <div className="h-4 bg-muted rounded-md animate-pulse"></div>
        <div className="h-4 bg-muted rounded-md animate-pulse"></div>
        <div className="h-4 w-5/6 bg-muted rounded-md animate-pulse"></div>
      </div>
      <div className="space-y-1">
        <div className="h-4 w-1/2 bg-primary/20 rounded-md flex items-center">
          <div className="h-4 w-3/5 bg-primary/50 rounded-md"></div>
        </div>
        <div className="text-xs text-muted-foreground">Originality score: 60%</div>
      </div>
      <div className="p-3 border border-yellow-200 bg-yellow-50 rounded-md flex gap-2">
        <ShieldCheck className="text-yellow-600 shrink-0 mt-0.5" size={16} />
        <div className="text-sm text-yellow-800">
          <span className="font-medium">Matched content detected.</span> 40% of text matches sources on the web. View sources.
        </div>
      </div>
    </div>
  </div>
);

const FeaturePreviewDetection = () => (
  <div className="bg-white shadow-lg rounded-xl p-6 w-full">
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <div className="h-6 w-1/2 bg-muted rounded-md animate-pulse"></div>
        <div className="px-3 py-1 bg-red-100 text-red-700 rounded-full text-sm font-medium">AI Detected</div>
      </div>
      <div className="space-y-2">
        <div className="h-4 bg-muted rounded-md animate-pulse"></div>
        <div className="h-4 bg-muted rounded-md animate-pulse"></div>
        <div className="h-4 w-5/6 bg-muted rounded-md animate-pulse"></div>
      </div>
      <div className="space-y-1">
        <div className="h-4 w-full bg-muted rounded-md flex items-center">
          <div className="h-4 w-4/5 bg-red-400 rounded-md"></div>
        </div>
        <div className="flex justify-between text-xs">
          <span className="text-muted-foreground">AI Probability</span>
          <span className="font-medium">84%</span>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <div className="p-2 border border-border rounded-md">
          <div className="text-xs text-muted-foreground mb-1">Repetitive Patterns</div>
          <div className="text-sm font-medium">High</div>
        </div>
        <div className="p-2 border border-border rounded-md">
          <div className="text-xs text-muted-foreground mb-1">Complexity</div>
          <div className="text-sm font-medium">Low</div>
        </div>
      </div>
    </div>
  </div>
);

const FeaturePreviewHumanize = () => (
  <div className="bg-white shadow-lg rounded-xl p-6 w-full">
    <div className="space-y-4">
      <div className="h-6 w-1/2 bg-muted rounded-md animate-pulse"></div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <div className="text-xs text-muted-foreground">Original (AI)</div>
          <div className="p-3 bg-muted/50 rounded-md h-24 text-sm overflow-hidden">
            <div className="h-3 bg-muted rounded-md w-full mb-1"></div>
            <div className="h-3 bg-muted rounded-md w-5/6 mb-1"></div>
            <div className="h-3 bg-muted rounded-md w-full mb-1"></div>
            <div className="h-3 bg-muted rounded-md w-4/5 mb-1"></div>
          </div>
        </div>
        <div className="space-y-2">
          <div className="text-xs text-muted-foreground">Humanized</div>
          <div className="p-3 bg-primary/5 border border-primary/20 rounded-md h-24 text-sm overflow-hidden">
            <div className="h-3 bg-primary/20 rounded-md w-4/5 mb-1"></div>
            <div className="h-3 bg-primary/20 rounded-md w-full mb-1"></div>
            <div className="h-3 bg-primary/20 rounded-md w-5/6 mb-1"></div>
            <div className="h-3 bg-primary/20 rounded-md w-3/4 mb-1"></div>
          </div>
        </div>
      </div>
      <div className="flex gap-2 items-center">
        <div className="h-4 w-1/3 bg-green-100 rounded-md flex items-center">
          <div className="h-4 w-full bg-green-400 rounded-md"></div>
        </div>
        <span className="text-xs text-green-600 font-medium">100% Human Score</span>
      </div>
      <div className="p-3 border border-green-200 bg-green-50 rounded-md flex gap-2">
        <RefreshCw className="text-green-600 shrink-0 mt-0.5" size={16} />
        <div className="text-sm text-green-800">
          <span className="font-medium">Successfully humanized.</span> Text will now pass AI detection tests.
        </div>
      </div>
    </div>
  </div>
);

export default FeatureShowcase;
